### ISSUE TITLE
Quest Support

### ISSUE THREAD

**Issue by eyefades** [sammyt291/FineHarvest#4]
Is it possible to get [Quest](https://www.spigotmc.org/resources/quests-1-8-1-20-set-up-goals-for-players.23696/) support added? Currently, if a player harvest via FineHarvest (holding right click) it does not count towards quest. 

Quest Task Config:
```
tasks:
  farming:
    amount: 5660
    type: farming
```
